// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import { ThemeProvider } from "next-themes";
// // import Navbar from "@/Component/Navbar";
// // import { ToastContainer } from "react-toastify";
// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // // export default function RootLayout({ children }) {
// //   // return (
// //   //   <html lang="en">
// //   //     <body
// //   //       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //   //     >
// //   //       <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
// //   //         {/* <Navbar /> */}
// //   //         <Navbar></Navbar>
// //   //         {/* Main content-e padding-top dewa hoyeche jate Navbar-er niche na dhuke jay */}
// //   //         <main className="pt-20 min-h-screen bg-white dark:bg-brand-darkBg transition-colors duration-300">
// //   //           {children}
// //   //         </main>
// //   //       </ThemeProvider>




     
// //   //     </body>
// //   //   </html>
// //   // );
// // // export default function RootLayout({ children }) {
// // //   return (
// // //     // suppressHydrationWarning add kora hoyeche
// // //     <html lang="en" suppressHydrationWarning> 
// // //       <body className="antialiased">
// // //         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
// // //           <Navbar />
       
// // // <main className="min-h-screen pt-20">
// // //  <ToastContainer position="top-right" autoClose={3000} />
  
// // // </main>
// // // {children}
// // //         </ThemeProvider>
// // //       </body>
// // //     </html>
// // //   );
// // // }
// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en" suppressHydrationWarning> 
// //       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
// //         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
// //           <Navbar />
// //           {/* ১. children-কে main ট্যাগের ভেতরে রাখতে হবে */}
// //           {/* ২. bg-white (Light) এবং dark:bg-[#060b13] (Dark) ক্লাস যোগ করতে হবে */}
// //           <main className="min-h-screen pt-20 bg-white dark:bg-[#060b13] transition-colors duration-300"> 
            
// //             {children}
// //           </main> 
// //         </ThemeProvider>
// //       </body>
// //     </html>
// //   );
// // }

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// // import { ThemeProvider } from "next-themes";
// import Navbar from "@/Component/Navbar";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css"; // Toast-এর স্টাইল পেতে এটি দরকার

// import { ThemeProvider } from "next-themes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning> 
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
         
      
//           {/* Main content area */}
//           <main className="min-h-screen pt-20 bg-white dark:bg-[#060b13] transition-colors duration-300"> 
//           <ThemeProvider attribute="class" defaultTheme="system" enableSystem>  
//                 <Navbar />
//              {children} </ThemeProvider>
           
//           </main>

//           {/* Toast notifications globally setup */}
//           {/* <ToastContainer position="top-right" autoClose={3000} /> */}
          
        
//       </body>
//     </html>
//   );
// }
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/Component/Navbar";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css"; 
// import { ThemeProvider } from "next-themes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "DermaCare Hub - Beauty & Wellness",
//   description: "Advanced skincare and haircare solutions",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning> 
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         {/* ThemeProvider shobar upore thakbe */}
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
//           <Navbar />
          
//           {/* Main content-e background color add kora hoyeche dark mode support shohok */}
//           <main className="min-h-screen pt-20 bg-white dark:bg-[#060b13] transition-colors duration-300"> 
//             {children} 
//           </main>

//           {/* ToastContainer global bhabe thakbe */}
//           <ToastContainer position="top-right" autoClose={3000} />
          
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/component/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; // Toast CSS যোগ করতে ভুলবেন না
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DermaCare Hub",
  description: "Your skincare partner",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" class="light" >
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         {/* attribute="class" নিশ্চিত করে যে dark ক্লাসটি কাজ করবে */}
//         <ThemeProvider attribute="class"  defaultTheme="light" enableSystem={false}>
//           <Navbar />
          
//           {/* এই main ট্যাগটিই পুরো পেজের ব্যাকগ্রাউন্ড কন্ট্রোল করবে */}
//           <main className="min-h-screen pt-20 bg-white dark:bg-[#060b13] transition-colors duration-300">
//             <ToastContainer position="top-right" autoClose={3000} />
//             {children}
//           </main>
          
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
// src/app/layout.jsx
export default function RootLayout({ children }) {
  return (
    // এখানে class="light" রাখার দরকার নেই, এটিই এরর দিচ্ছে
    <html lang="en" suppressHydrationWarning> 
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ThemeProvider নিজে থেকেই html ট্যাগে dark/light ক্লাস বসাবে */}
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <Navbar />
  <main className="min-h-screen pt-20">
  {children}
</main>
<Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}