import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/Component/Navbar";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
  // return (
  //   <html lang="en">
  //     <body
  //       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //     >
  //       <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
  //         {/* <Navbar /> */}
  //         <Navbar></Navbar>
  //         {/* Main content-e padding-top dewa hoyeche jate Navbar-er niche na dhuke jay */}
  //         <main className="pt-20 min-h-screen bg-white dark:bg-brand-darkBg transition-colors duration-300">
  //           {children}
  //         </main>
  //       </ThemeProvider>




     
  //     </body>
  //   </html>
  // );
export default function RootLayout({ children }) {
  return (
    // suppressHydrationWarning add kora hoyeche
    <html lang="en" suppressHydrationWarning> 
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
       
<main className="min-h-screen pt-20">
 <ToastContainer position="top-right" autoClose={3000} />
  {children}
</main>
        </ThemeProvider>
      </body>
    </html>
  );
}

// }
// import Navbar from "@/Component/Navbar";
// import { ThemeProvider } from "next-themes";
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className="antialiased">
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//           <Navbar />
//           {/* Nicher line-e bg-white thaka joriuri */}
//           <main className="min-h-screen bg-white dark:bg-[#0D4C4F] transition-colors duration-300 pt-20">
//             {children}
//           </main>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }